---
hero_image: images/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Create Your Own World
description: Learn how to create your own open world adventure game.
original_url: https://codeclubprojects.org/en-GB/scratch/create-your-own-world
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduction
- title: Coding your player
- title: 'Challenge: Moving in all four directions'
- title: 'Challenge: Fixing your player''s movement'
- title: Coding your world
- title: 'Challenge: Moving to the previous room'
- title: Signs
- title: 'Challenge: Treasure!'
- title: People
- title: 'Challenge: Improving your person'
- title: 'Challenge: More enemies'
- title: Collecting coins
- title: 'Challenge: More coins'
- title: Doors and keys
- title: 'Challenge: Create your own world'

