hero_image: images/create-your-own-world.png
title: Create Your Own World
description: Learn how to create your own open world adventure game.
original_url: https://codeclubprojects.org/en-GB/scratch/create-your-own-world
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduction
- title: What you will need
- title: Moving the player
- title: Solid walls
- title: Coding your world
- title: Signs
- title: 'Challenge: Treasure!'
- title: People
- title: 'Challenge: Improving your person'
- title: 'Challenge: More enemies'
- title: Collecting coins
- title: 'Challenge: More coins'
- title: Doors and keys
- title: 'Challenge: Create your own world'
